# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170513_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('category_name', models.CharField(blank=True, max_length=500)),
                ('fsq_id', models.CharField(max_length=400)),
                ('users', models.ManyToManyField(to='login.Profile')),
            ],
        ),
    ]
