# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='List_followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='User_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='places',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='places',
            name='fsq_id',
        ),
        migrations.RemoveField(
            model_name='places',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='places',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='places',
            name='name',
        ),
        migrations.RemoveField(
            model_name='places',
            name='users',
        ),
        migrations.AddField(
            model_name='list_followers',
            name='list',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_list'),
        ),
        migrations.AddField(
            model_name='cities',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_list'),
        ),
        migrations.AddField(
            model_name='places',
            name='list',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_list'),
        ),
    ]
