# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20170518_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_list'),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Profile'),
        ),
    ]
