# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20170519_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_followers',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='list_followers',
            name='list',
        ),
        migrations.AddField(
            model_name='user_list',
            name='followers',
            field=models.ManyToManyField(to='login.Profile'),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='login.Profile'),
        ),
        migrations.DeleteModel(
            name='List_followers',
        ),
    ]
