# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20170523_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities',
            old_name='name',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cities',
        ),
        migrations.AddField(
            model_name='cities',
            name='city_user',
            field=models.ManyToManyField(to='login.Profile'),
        ),
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.CharField(default='dao', max_length=30),
        ),
    ]
