# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20170523_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='name',
            field=models.CharField(default='dao', max_length=100),
        ),
    ]
