# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_lists_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='city',
            field=models.CharField(default='dao', max_length=30, unique='true'),
        ),
        migrations.AlterField(
            model_name='lists',
            name='name',
            field=models.CharField(default='dao', max_length=100, unique='true'),
        ),
    ]
