# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20170525_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='city',
        ),
        migrations.AlterField(
            model_name='cities',
            name='city',
            field=models.CharField(default='dao1', max_length=30, unique='true'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='country',
            field=models.CharField(default='dao2', max_length=30),
        ),
        migrations.AlterField(
            model_name='lists',
            name='name',
            field=models.CharField(default='dao4', max_length=100, unique='true'),
        ),
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(default='dao3', max_length=30),
        ),
    ]
