# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20170528_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login.Cities'),
        ),
    ]
