# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_lists_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='name',
            field=models.CharField(default='dao4', max_length=100),
        ),
    ]
