# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20170528_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='places',
        ),
        migrations.AddField(
            model_name='places',
            name='address',
            field=models.CharField(default='dao3', max_length=100),
        ),
        migrations.AddField(
            model_name='places',
            name='category',
            field=models.CharField(default='dao3', max_length=100),
        ),
        migrations.AddField(
            model_name='places',
            name='category_id',
            field=models.CharField(default='dao3', max_length=100),
        ),
        migrations.AddField(
            model_name='places',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Cities'),
        ),
        migrations.AddField(
            model_name='places',
            name='lat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='lists',
            field=models.ManyToManyField(to='login.Lists'),
        ),
        migrations.AddField(
            model_name='places',
            name='lng',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='venue_id',
            field=models.CharField(default='dao3', max_length=50),
        ),
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(default='dao3', max_length=100),
        ),
    ]
