# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20170531_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(default='dao3', max_length=30),
        ),
    ]
